version: '2'
services:
    web:
        build:
          context: .
          dockerfile: helpers/Dockerfile
        depends_on:
            - db
        ports:
            - "8888:80"
        volumes:
            - ./src/:/var/www/html/
        hostname: web
    db:
        image: mysql:5.7
        environment:
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_DATABASE: cache
        ports:
            - "33306:3306"
        command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --query_cache_type=1 --query_cache_size=1M
